RABBITMQ_HOST = "127.0.0.1"
RABBITMQ_PORT = 5672
RABBITMQ_USER = "admin"
RABBITMQ_PASSWORD = "admin123"
RABBITMQ_VHOST = "/"

AI_RMQ_EXCHANGE = "ai.exchange"
AI_RMQ_RESULTS_ROUTING_KEY = "job.result"
AI_RMQ_STT_QUEUE = "ai.stt.jobs"
AI_RMQ_STT_ROUTING_KEY = "job.stt.create"
AI_RMQ_OCR_QUEUE = "ai.ocr.jobs"
AI_RMQ_OCR_ROUTING_KEY = "job.ocr.create"
AI_RMQ_HEATMAP_QUEUE = "ai.heatmap.jobs"
AI_RMQ_HEATMAP_ROUTING_KEY = "analytics.generate_heatmap"

LARAVEL_BASE_URL = "http:// 172.20.10.8:8000"
LARAVEL_API_PREFIX = "/api"
LARAVEL_VIOLATIONS_API = "http:// 172.20.10.8:8000/api/ai_violations"
LARAVEL_API_TIMEOUT = 30

WHISPER_MODEL_NAME = "medium"
WHISPER_LANGUAGE = "ar"

LMSTUDIO_BASE_URL = "http:// 172.20.10.8:1234"
LMSTUDIO_MODEL = "mistralai/mistral-7b-instruct-v0.3"
LMSTUDIO_TIMEOUT = 120

MONGO_URL = "mongodb://127.0.0.1:27017"
MONGO_DB = "ai_service"
MONGO_OCR_COLLECTION = "plate_ocr_results"

OLLAMA_URL = "http://127.0.0.1:11434/api/generate"
OLLAMA_MODEL = "qwen2.5vl:3b"
OLLAMA_TIMEOUT = 300
OLLAMA_NUM_CTX = 4096
OLLAMA_NUM_PREDICT = 700
OLLAMA_RETRIES = 2

HEATMAP_CACHE_TTL_SECONDS = 3600
HEATMAP_GRID_DEFAULT_METERS = 800
HEATMAP_GRID_MIN_METERS = 50
HEATMAP_GRID_MAX_METERS = 2000
HEATMAP_GRID_MAX_CELLS = 2500
HEATMAP_TOP_N = 5
HEATMAP_BANDWIDTH_METERS = 700
HEATMAP_SYNTHETIC_POINTS = 80
HEATMAP_VIOLATIONS_PAGE_SIZE = 120
HEATMAP_MIN_VISIBLE_INTENSITY = 0.02
HEATMAP_MAX_RETURN_POINTS = 60
