SECRET_KEY = "change-me"
DEBUG = False
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

RABBITMQ_HOST = "127.0.0.1"
RABBITMQ_PORT = 5672
RABBITMQ_USER = "admin"
RABBITMQ_PASSWORD = "admin123"
RABBITMQ_VHOST = "/"

AI_RMQ_EXCHANGE = "ai.exchange"
AI_RMQ_RESULTS_ROUTING_KEY = "job.result"
AI_RMQ_STT_QUEUE = "ai.stt.jobs"
AI_RMQ_STT_ROUTING_KEY = "job.stt.create"
AI_RMQ_OCR_QUEUE = "ai.ocr.jobs"
AI_RMQ_OCR_ROUTING_KEY = "job.ocr.create"
AI_RMQ_HEATMAP_QUEUE = "ai.heatmap.jobs"
AI_RMQ_HEATMAP_ROUTING_KEY = "analytics.generate_heatmap"
AI_RMQ_HEATMAP_PREDICTION_QUEUE = "ai.heatmap.prediction.jobs"
AI_RMQ_HEATMAP_PREDICTION_ROUTING_KEY = "heatmap.prediction.request"

LARAVEL_BASE_URL = "http://192.168.0.119:8000"
LARAVEL_API_PREFIX = "/api"
LARAVEL_VIOLATIONS_API = "http://192.168.0.119:8000/api/ai_violations"
LARAVEL_API_TIMEOUT = 30

WHISPER_MODEL_NAME = "medium"
WHISPER_LANGUAGE = "ar"

LMSTUDIO_BASE_URL = "http://192.168.0.119:1234"
LMSTUDIO_MODEL = "mistralai/mistral-7b-instruct-v0.3"
LMSTUDIO_TIMEOUT = 120

MONGO_URL = "mongodb://127.0.0.1:27017"
MONGO_DB = "ai_service"
MONGO_OCR_COLLECTION = "plate_ocr_results"

OLLAMA_URL = "http://127.0.0.1:11434/api/generate"
OLLAMA_MODEL = "qwen2.5vl:3b"
OLLAMA_TIMEOUT = 300
OLLAMA_TIMEOUT_SECONDS = 20
OLLAMA_NUM_CTX = 4096
OLLAMA_NUM_PREDICT = 700
OLLAMA_RETRIES = 2

HEATMAP_PREDICTION_LLM_PROVIDER = "qwen_api"
QWEN_API_KEY = "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"
QWEN_BASE_URL = "https://openrouter.ai/api/v1"
QWEN_MODEL = "qwen/qwen-2.5-72b-instruct"
QWEN_TIMEOUT_SECONDS = 20
QWEN_MAX_TOKENS = 700
QWEN_TEMPERATURE = 0.2
HEATMAP_PREDICTION_OLLAMA_MODEL = "qwen3:8b"
HEATMAP_PREDICTION_LMSTUDIO_MODEL = "qwen3-8b"
HEATMAP_PREDICTION_OLLAMA_NUM_PREDICT = 480
HEATMAP_PREDICTION_OLLAMA_RETRIES = 1
HEATMAP_PREDICTION_MAX_HOTSPOTS = 5
HEATMAP_PREDICTION_MIN_CONFIDENCE = 0.35

HEATMAP_CACHE_TTL_SECONDS = 3600
HEATMAP_GRID_DEFAULT_METERS = 800
HEATMAP_GRID_MIN_METERS = 50
HEATMAP_GRID_MAX_METERS = 2000
HEATMAP_GRID_MAX_CELLS = 2500
HEATMAP_TOP_N = 10
HEATMAP_BANDWIDTH_METERS = 350
HEATMAP_SYNTHETIC_POINTS = 80
HEATMAP_VIOLATIONS_PAGE_SIZE = 120
HEATMAP_MIN_VISIBLE_INTENSITY = 0.005
HEATMAP_MAX_RETURN_POINTS = 120
